// Auto-generated by generate_data.py -- do not edit manually
// Generated from env repos at /home/aidanby
const CALIBRATOR_DATA = {
  "models": [
    "claude-sonnet-4-6",
    "gemini-3.1-pro-preview",
    "gemini-2.5-flash",
    "mistral-large-3",
    "kimi-k2.5"
  ],
  "modelNames": {
    "claude-sonnet-4-6": "Claude Sonnet 4.6",
    "gemini-2.5-flash": "Gemini 2.5 Flash",
    "gemini-3.1-pro-preview": "Gemini 3.1 Pro",
    "kimi-k2.5": "Kimi K2.5",
    "mistral-large-3": "Mistral Large 3"
  },
  "envs": [
    {
      "id": "hw-cbmc",
      "name": "Hardware Verification",
      "desc": "Agents debug and formally verify hardware designs against temporal and safety properties.",
      "tasks": [
        {
          "n": "Irqctrl",
          "d": "Write formal proofs that a verifier accepts.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            0.0,
            0.0,
            0.0
          ]
        },
        {
          "n": "Fix Regfile Fwd",
          "d": "Write formal proofs that a verifier accepts.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            0.4857,
            0.2173,
            0.2173,
            0.2173,
            0.2173
          ]
        },
        {
          "n": "Fix Branch Pred",
          "d": "Write formal proofs that a verifier accepts.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            0.2173,
            0.7965,
            0.2173,
            0.2173,
            0.2173
          ]
        }
      ]
    },
    {
      "id": "lean",
      "name": "Theorem Proving",
      "desc": "Agents construct formal proofs covering compiler correctness, data structure invariants, and abstract algebra.",
      "tasks": [
        {
          "n": "Ackermann Level3",
          "d": "Write formal proofs that a verifier accepts.",
          "c": 0.6,
          "s": 10.0,
          "f": [
            1.0,
            1.0,
            0.1214,
            0.0,
            0.4369
          ]
        },
        {
          "n": "Nat Divisibility",
          "d": "Write formal proofs that a verifier accepts.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.7374,
            1.0,
            0.7374,
            0.097,
            0.0001
          ]
        },
        {
          "n": "Nat Induction Hard",
          "d": "Write formal proofs that a verifier accepts.",
          "c": 0.25,
          "s": 6.0,
          "f": [
            0.0847,
            1.0,
            0.0,
            0.0,
            0.0847
          ]
        }
      ]
    },
    {
      "id": "csparse",
      "name": "Systems Migration",
      "desc": "Agents port numerical computing libraries to a memory-safe language with formal verification.",
      "tasks": [
        {
          "n": "Vec Scale",
          "d": "Port a numerical computing function to a verified implementation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.7385,
            0.6864,
            0.7633,
            0.0,
            0.7746
          ]
        },
        {
          "n": "Norm",
          "d": "Port a numerical computing function to a verified implementation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.4998,
            0.4576,
            0.0,
            0.0,
            0.0
          ]
        },
        {
          "n": "Matvec",
          "d": "Port a numerical computing function to a verified implementation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.3364,
            0.3443,
            0.2387,
            0.0,
            0.0
          ]
        }
      ]
    },
    {
      "id": "congestion",
      "name": "Network Protocols",
      "desc": "Agents implement and fix congestion control algorithms, verified against performance and fairness targets.",
      "tasks": [
        {
          "n": "Flow Fairness",
          "d": "Write formal proofs that a verifier accepts.",
          "c": 0.45,
          "s": 8.0,
          "f": [
            1.0,
            0.0,
            0.0,
            0.0,
            0.0
          ]
        },
        {
          "n": "Fix Three Bugs",
          "d": "Fix a network protocol to meet performance targets.",
          "c": 0.93,
          "s": 8.0,
          "f": [
            0.6415,
            0.3636,
            0.0,
            0.4896,
            0.3464
          ]
        },
        {
          "n": "Fix AIMD",
          "d": "Fix a network protocol to meet performance targets.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            0.3007,
            0.0,
            0.0,
            0.3007,
            0.1948
          ]
        }
      ]
    },
    {
      "id": "consensus",
      "name": "Distributed Systems",
      "desc": "Agents build and repair consensus protocols, verified against safety and liveness specifications.",
      "tasks": [
        {
          "n": "Fix Consistent Hash Replication",
          "d": "Fix bugs in a distributed protocol implementation.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            1.0,
            0.0,
            0.0,
            0.5215,
            0.0
          ]
        },
        {
          "n": "Implement BFT Kv Store",
          "d": "Implement a distributed protocol from specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            0.4071,
            0.1307,
            0.0307,
            0.1307,
            0.013
          ]
        },
        {
          "n": "Fix Snapshot Replication",
          "d": "Fix bugs in a distributed protocol implementation.",
          "c": 0.8,
          "s": 8.0,
          "f": [
            0.3063,
            0.0,
            0.0,
            0.0,
            0.0
          ]
        }
      ]
    },
    {
      "id": "cedar",
      "name": "Authorization",
      "desc": "Agents write and verify authorization policies against security property specifications.",
      "tasks": [
        {
          "n": "Fix Ip Time Geo Policies",
          "d": "Fix bugs in an authorization policy system.",
          "c": 0.87,
          "s": 8.0,
          "f": [
            1.0,
            0.5776,
            0.5776,
            0.5776,
            0.0
          ]
        },
        {
          "n": "Debug Recursive Hierarchy Access",
          "d": "Build or verify authorization policies.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            0.5812,
            0.7244,
            0.0,
            0.7244,
            0.5812
          ]
        },
        {
          "n": "Implement And Verify Refactoring",
          "d": "Write formal proofs that a verifier accepts.",
          "c": 0.3,
          "s": 8.0,
          "f": [
            0.3361,
            0.0,
            0.0,
            0.3561,
            0.0
          ]
        }
      ]
    }
  ]
};
