// Auto-generated by generate_data.py -- do not edit manually
const CALIBRATOR_DATA = {
  "models": [
    "claude-sonnet-4-6",
    "gemini-3.1-pro-preview",
    "gemini-2.5-flash",
    "Mistral-large-3",
    "kimi-k2.5"
  ],
  "modelNames": {
    "claude-sonnet-4-6": "Claude Sonnet 4.6",
    "gemini-2.5-flash": "Gemini 2.5 Flash",
    "gemini-3.1-pro-preview": "Gemini 3.1 Pro",
    "kimi-k2.5": "Kimi K2.5",
    "Mistral-large-3": "Mistral Large 3"
  },
  "envs": [
    {
      "id": "hw-cbmc",
      "name": "Hardware Verification",
      "desc": "Agents fix bugs in SystemVerilog designs and write formal assertions, verified by EBMC bounded model checker.",
      "tasks": [
        {
          "n": "Fix TLB Ctrl",
          "d": "Debug a tlb ctrl circuit until all formal properties prove.",
          "c": 0.75,
          "s": 10.0,
          "f": [
            null,
            1.0,
            0.0243,
            0.0,
            1.0
          ]
        },
        {
          "n": "Fix FIFO Async",
          "d": "Debug a fifo async circuit until all formal properties prove.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            0.4857,
            0.4857,
            0.078,
            0.0,
            0.078
          ]
        },
        {
          "n": "Fix Restoring Div",
          "d": "Debug a restoring div circuit until all formal properties prove.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            0.047,
            0.0,
            0.047
          ]
        }
      ]
    },
    {
      "id": "lean",
      "name": "Theorem Proving",
      "desc": "Agents construct formal proofs in Lean 4 covering compiler correctness, data structure invariants, and rewriting systems.",
      "tasks": [
        {
          "n": "Binary Search",
          "d": "Construct Lean 4 proofs for binary search.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.0,
            1.0,
            1.0,
            0.0,
            1.0
          ]
        },
        {
          "n": "Increasing Triplet",
          "d": "Construct Lean 4 proofs for increasing triplet.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.734,
            0.734,
            0.734,
            0.734,
            0.734
          ]
        },
        {
          "n": "Ackermann Level3",
          "d": "Construct Lean 4 proofs for ackermann level3.",
          "c": 0.6,
          "s": 10.0,
          "f": [
            1.0,
            1.0,
            0.5079,
            0.0,
            1.0
          ]
        }
      ]
    },
    {
      "id": "csparse",
      "name": "Systems Migration",
      "desc": "Agents migrate C sparse matrix libraries to idiomatic Rust with Verus verification annotations.",
      "tasks": [
        {
          "n": "Mat Diag",
          "d": "Port the CSparse mat diag function from C to idiomatic Rust.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.3462,
            0.3506,
            0.2879,
            0.2681,
            0.0
          ]
        },
        {
          "n": "Csparse Norm",
          "d": "Port the CSparse norm function from C to idiomatic Rust.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.4998,
            0.4676,
            0.0,
            0.0,
            0.2367
          ]
        },
        {
          "n": "Csparse Usolve",
          "d": "Port the CSparse usolve function from C to idiomatic Rust.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.4249,
            0.3511,
            0.0,
            0.0,
            0.3736
          ]
        }
      ]
    },
    {
      "id": "consensus",
      "name": "Distributed Systems",
      "desc": "Agents build and repair distributed consensus protocols with Dafny proofs of safety properties.",
      "tasks": [
        {
          "n": "Fix Snapshot Replication",
          "d": "Fix bugs in a snapshot replication protocol implementation.",
          "c": 0.8,
          "s": 8.0,
          "f": [
            0.3063,
            0.0,
            0.0,
            0.0,
            0.0
          ]
        },
        {
          "n": "Implement BFT Kv Store",
          "d": "Implement bft kv store from the protocol specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            0.4071,
            0.1307,
            0.0307,
            0.0,
            0.013
          ]
        },
        {
          "n": "Fix Consistent Hash Replication",
          "d": "Fix bugs in a consistent hash replication protocol implementation.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            0.0,
            0.5215,
            0.0
          ]
        }
      ]
    },
    {
      "id": "cedar",
      "name": "Authorization",
      "desc": "Agents write Cedar authorization policies and prove security properties in Lean 4.",
      "tasks": [
        {
          "n": "Implement And Verify Refactoring",
          "d": "Prove implement and refactoring safety properties in Dafny.",
          "c": 0.3,
          "s": 8.0,
          "f": [
            0.3361,
            0.0,
            0.0,
            0.0,
            0.0
          ]
        },
        {
          "n": "Debug Recursive Hierarchy Access",
          "d": "Build authorization policies for debug recursive hierarchy access.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            0.5812,
            0.7244,
            0.0,
            0.0,
            0.5812
          ]
        },
        {
          "n": "Fix Action Group Conflicts",
          "d": "Fix authorization policy bugs in action group conflicts.",
          "c": 0.62,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            0.0,
            0.6178
          ]
        }
      ]
    }
  ]
};
