// Auto-generated by generate_data.py -- do not edit manually
// Generated from env repos at /home/aidanby
const CALIBRATOR_DATA = {
  "models": [
    "claude-sonnet-4-6",
    "gemini-2.5-flash",
    "gemini-3.1-pro-preview",
    "kimi-k2.5",
    "Mistral-large-3"
  ],
  "modelNames": {
    "claude-sonnet-4-6": "Claude Sonnet 4",
    "gemini-2.5-flash": "Gemini 2.5 Flash",
    "gemini-3.1-pro-preview": "Gemini 3.1 Pro",
    "kimi-k2.5": "Kimi K2.5",
    "Mistral-large-3": "Mistral Large 3"
  },
  "envs": [
    {
      "id": "hw-cbmc",
      "name": "Hardware Verification",
      "desc": "Agents fix bugs in SystemVerilog designs and write formal assertions, verified by EBMC bounded model checker.",
      "tasks": [
        {
          "n": "Fix ARB Lock",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.65,
          "s": 8.0,
          "f": [
            0.1493,
            0.1493,
            1.0,
            0.1493,
            0.1493
          ]
        },
        {
          "n": "Fix Booth Mul",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.1436,
            1.0,
            0.1436,
            0.1436
          ]
        },
        {
          "n": "Fix Branch Pred",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            0.2172,
            0.2172,
            0.7964,
            0.2172,
            0.2172
          ]
        },
        {
          "n": "Fix Cache Ctrl",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            0.7964,
            0.4857,
            0.7964,
            0.4857,
            0.4857
          ]
        },
        {
          "n": "Fix DMA Engine",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            0.078,
            0.078,
            0.2172,
            0.078,
            0.078
          ]
        },
        {
          "n": "Fix FIFO Async",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            0.4857,
            0.078,
            0.4857,
            0.078,
            0.0
          ]
        },
        {
          "n": "Fix FIFO Credit",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            1.0,
            0.7964,
            1.0,
            0.078,
            0.078
          ]
        },
        {
          "n": "Fix FIFO Ptrs",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            1.0,
            0.4857
          ]
        },
        {
          "n": "Fix I2C Ctrl",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.4049,
            1.0,
            0.4049,
            0.4049
          ]
        },
        {
          "n": "Fix LFSR",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            1.0,
            0.0125
          ]
        },
        {
          "n": "Fix Mem Ctrl",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            0.0806,
            0.078,
            0.7964,
            0.078,
            0.078
          ]
        },
        {
          "n": "Fix Regfile Fwd",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.75,
          "s": 8.0,
          "f": [
            0.4857,
            0.2172,
            0.4857,
            0.2172,
            0.2172
          ]
        },
        {
          "n": "Fix Restoring Div",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.047,
            1.0,
            0.047,
            0.0
          ]
        },
        {
          "n": "Fix SMV Ring3",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            1.0,
            1.0
          ]
        },
        {
          "n": "Fix SPI Slave",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.4049,
            0.4049,
            0.8529,
            0.0739,
            0.0739
          ]
        },
        {
          "n": "Fix Timer IRQ",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.65,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            1.0,
            1.0
          ]
        },
        {
          "n": "Fix TLB Ctrl",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.75,
          "s": 10.0,
          "f": [
            null,
            0.0243,
            1.0,
            1.0,
            0.0
          ]
        },
        {
          "n": "Fix UART Rx",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.65,
          "s": 8.0,
          "f": [
            1.0,
            0.8611,
            1.0,
            1.0,
            0.8611
          ]
        },
        {
          "n": "Implement Arb3",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.5192,
            1.0,
            0.0578,
            0.0
          ]
        },
        {
          "n": "Write Assertions Irqctrl",
          "d": "Write formal SVA assertions to verify hardware correctness properties.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            null,
            0.0,
            null,
            0.0,
            0.0
          ]
        },
        {
          "n": "Write Assertions Tasksched",
          "d": "Write formal SVA assertions to verify hardware correctness properties.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Write Assertions Txnmon",
          "d": "Write formal SVA assertions to verify hardware correctness properties.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            null,
            0.0,
            0.0,
            0.0,
            0.0
          ]
        },
        {
          "n": "Write Assertions Wdogtimer",
          "d": "Write formal SVA assertions to verify hardware correctness properties.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            null,
            0.0,
            0.0,
            0.0,
            0.0
          ]
        }
      ]
    },
    {
      "id": "lean",
      "name": "Theorem Proving",
      "desc": "Agents construct formal proofs in Lean 4 covering compiler correctness, data structure invariants, and rewriting systems.",
      "tasks": [
        {
          "n": "Ackermann Level3",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.6,
          "s": 10.0,
          "f": [
            1.0,
            0.031,
            1.0,
            0.0,
            null
          ]
        },
        {
          "n": "Binary Search",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.0,
            1.0,
            0.6514,
            0.0764,
            null
          ]
        },
        {
          "n": "Church Rosser",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.45,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Compiler Correctness",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.45,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fib Add Formula",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.3247,
            0.3483,
            0.3247,
            0.3247,
            null
          ]
        },
        {
          "n": "First Duplicate",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            1.0,
            null
          ]
        },
        {
          "n": "Fix Proof Errors",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            0.2161,
            null
          ]
        },
        {
          "n": "Fix Wrong Lemma",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            1.0,
            null
          ]
        },
        {
          "n": "Increasing Triplet",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.7374,
            0.7374,
            0.7374,
            0.7374,
            null
          ]
        },
        {
          "n": "Last Digit Squares",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.0,
            1.0,
            0.0,
            null
          ]
        },
        {
          "n": "List Advanced",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.2378,
            1.0,
            0.2378,
            null
          ]
        },
        {
          "n": "List Filter",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.0608,
            1.0,
            0.0037,
            null
          ]
        },
        {
          "n": "Longest Streak",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            1.0,
            null
          ]
        },
        {
          "n": "Majority Element",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.0,
            0.4397,
            0.6873,
            0.2231,
            null
          ]
        },
        {
          "n": "Max Subarray",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.6633,
            0.6633,
            0.1534,
            0.6633,
            null
          ]
        },
        {
          "n": "Merge Sorted",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.0052,
            0.0,
            0.4123,
            null
          ]
        },
        {
          "n": "Nat Arith Combined",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.005,
            0.1738,
            0.0,
            null
          ]
        },
        {
          "n": "Nat Divisibility",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.9308,
            0.1543,
            0.0903,
            0.0001,
            null
          ]
        },
        {
          "n": "Nat Induction Hard",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.7026,
            0.0052,
            1.0,
            0.0847,
            null
          ]
        },
        {
          "n": "Partition Evens Odds",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.0047,
            1.0,
            0.0,
            null
          ]
        },
        {
          "n": "Prime Factor Exists",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.6,
          "s": 10.0,
          "f": [
            1.0,
            0.0003,
            1.0,
            0.0,
            null
          ]
        },
        {
          "n": "Pythagorean Div3",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            1.0,
            0.0001,
            0.0094,
            0.0,
            null
          ]
        },
        {
          "n": "Red Black Invariant",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.45,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Regex Derivative",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.45,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Sqrt2 Irrational",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.6,
          "s": 10.0,
          "f": [
            0.4383,
            0.2855,
            0.4383,
            0.4244,
            null
          ]
        },
        {
          "n": "Sqrt3 Irrational",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.6,
          "s": 10.0,
          "f": [
            0.4244,
            0.2855,
            0.2765,
            0.2765,
            null
          ]
        },
        {
          "n": "Squares Mod Arith",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.6,
          "s": 10.0,
          "f": [
            1.0,
            0.0,
            0.0608,
            0.0,
            null
          ]
        },
        {
          "n": "Stock Profit",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.7374,
            1.0,
            1.0,
            0.0498,
            null
          ]
        },
        {
          "n": "Two Sum",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.55,
          "s": 8.0,
          "f": [
            0.4123,
            0.4123,
            1.0,
            0.4123,
            null
          ]
        },
        {
          "n": "Well Founded Order",
          "d": "Replace sorry placeholders with valid Lean 4 proofs.",
          "c": 0.45,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        }
      ]
    },
    {
      "id": "csparse",
      "name": "Systems Migration",
      "desc": "Agents migrate C sparse matrix libraries to idiomatic Rust with Verus verification annotations.",
      "tasks": [
        {
          "n": "Csc Col Norm",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.4301,
            0.6767,
            0.296,
            0.0,
            null
          ]
        },
        {
          "n": "Csc Filter",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.1817,
            0.1679,
            0.1631,
            0.1624,
            null
          ]
        },
        {
          "n": "Csc Matvec",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.3364,
            0.2387,
            0.3443,
            0.0,
            null
          ]
        },
        {
          "n": "Csc Nnz",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.2969,
            0.4851,
            0.2723,
            0.2731,
            null
          ]
        },
        {
          "n": "Csparse Cumsum",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.2708,
            0.2693,
            0.3046,
            0.2727,
            null
          ]
        },
        {
          "n": "Csparse Dfs",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.1183,
            0.0,
            0.0,
            0.1716,
            null
          ]
        },
        {
          "n": "Csparse Gaxpy",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.3123,
            0.3171,
            0.3145,
            0.3005,
            null
          ]
        },
        {
          "n": "Csparse Ipvec",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.3212,
            0.2616,
            0.469,
            0.2866,
            null
          ]
        },
        {
          "n": "Csparse Lsolve",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.4191,
            0.304,
            0.3285,
            0.2304,
            null
          ]
        },
        {
          "n": "Csparse Lu",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.0,
            0.0,
            0.0,
            0.0,
            null
          ]
        },
        {
          "n": "Csparse Multiply",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.1,
            0.0,
            0.0861,
            0.1104,
            null
          ]
        },
        {
          "n": "Csparse Norm",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.4998,
            0.0,
            0.4676,
            0.2367,
            null
          ]
        },
        {
          "n": "Csparse Pvec",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.3027,
            0.3139,
            0.6595,
            0.2884,
            null
          ]
        },
        {
          "n": "Csparse Reach",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.1781,
            0.0,
            0.2157,
            0.186,
            null
          ]
        },
        {
          "n": "Csparse Scatter",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.1843,
            0.0,
            0.2035,
            0.278,
            null
          ]
        },
        {
          "n": "Csparse Spsolve",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.1594,
            0.1229,
            0.1367,
            0.13,
            null
          ]
        },
        {
          "n": "Csparse Symperm",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.1063,
            0.0,
            0.1158,
            0.0824,
            null
          ]
        },
        {
          "n": "Csparse Transpose",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.2875,
            0.0,
            0.4167,
            0.2772,
            null
          ]
        },
        {
          "n": "Csparse Usolve",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.4249,
            0.0,
            0.3511,
            0.3736,
            null
          ]
        },
        {
          "n": "Dense To Csc",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.4399,
            0.3946,
            0.51,
            0.3851,
            null
          ]
        },
        {
          "n": "Mat Diag",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.3462,
            0.2879,
            0.3506,
            0.0,
            null
          ]
        },
        {
          "n": "Vec Add",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.3003,
            0.3373,
            0.3419,
            0.3499,
            null
          ]
        },
        {
          "n": "Vec Dot",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.2895,
            0.2788,
            0.208,
            0.2712,
            null
          ]
        },
        {
          "n": "Vec Max",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.4263,
            0.5561,
            0.4791,
            0.4534,
            null
          ]
        },
        {
          "n": "Vec Scale",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.7385,
            0.7696,
            0.8032,
            0.7746,
            null
          ]
        },
        {
          "n": "Verus Cumsum Proof",
          "d": "Fill in formal proof obligations so the verifier accepts.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Verus Perm Proof",
          "d": "Fill in formal proof obligations so the verifier accepts.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Verus Vec Add Proof",
          "d": "Fill in formal proof obligations so the verifier accepts.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        }
      ]
    },
    {
      "id": "congestion",
      "name": "Congestion Control",
      "desc": "Agents implement and fix TCP congestion control algorithms with Dafny formal verification of protocol safety.",
      "tasks": [
        {
          "n": "Fix AIMD",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fix Competing Flows",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fix Cubic Slow Start",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fix Cubic Units",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.98,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fix Fairness Under Competition",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.91,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fix Recovery Deadlock",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fix Slow Convergence",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fix Stale Ssthresh",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fix Three Bugs",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.93,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Fix Timeout Handling",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.96,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement BBR",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement Compound",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement Cubic",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.74,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement Fast Recovery",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.94,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement Ledbat",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement Loss Differentiated",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.94,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement Mult Decrease",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement PCC",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement Vegas",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.94,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Implement Westwood",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.92,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Tune High Bdp",
          "d": "Tune parameters to optimize performance on target workloads.",
          "c": 0.97,
          "s": 10.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Verify AIMD Safety",
          "d": "Fill in formal proof obligations so the verifier accepts.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Verify Flow Fairness",
          "d": "Fill in formal proof obligations so the verifier accepts.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        },
        {
          "n": "Verify Sliding Window",
          "d": "Fill in formal proof obligations so the verifier accepts.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            null,
            null,
            null,
            null,
            null
          ]
        }
      ]
    },
    {
      "id": "consensus",
      "name": "Distributed Systems",
      "desc": "Agents build and repair distributed consensus protocols with Dafny proofs of safety properties.",
      "tasks": [
        {
          "n": "Fix Consistent Hash Replication",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            1.0,
            0.0,
            1.0,
            0.0,
            0.5215
          ]
        },
        {
          "n": "Fix Distributed Lock",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.8,
          "s": 8.0,
          "f": [
            0.68,
            0.8624,
            1.0,
            0.68,
            0.8624
          ]
        },
        {
          "n": "Fix Distributed Snapshot",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            1.0,
            0.4025,
            1.0,
            0.0,
            0.0
          ]
        },
        {
          "n": "Fix Raft Safety",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            0.8198,
            0.8198,
            1.0,
            0.0,
            0.0
          ]
        },
        {
          "n": "Fix Raft Snapshot CRDT",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            0.4669,
            0.4669,
            0.7506,
            0.0,
            0.0
          ]
        },
        {
          "n": "Fix Snapshot Replication",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.8,
          "s": 8.0,
          "f": [
            0.3063,
            0.0,
            0.0,
            0.0,
            0.0
          ]
        },
        {
          "n": "Fix Txn Coordinator",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            0.0,
            1.0
          ]
        },
        {
          "n": "Hybrid Clock",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.9172,
            0.9172,
            0.9744,
            0.6134,
            0.6134
          ]
        },
        {
          "n": "Implement BFT Kv Store",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            0.4071,
            0.0307,
            0.1307,
            0.013,
            0.0
          ]
        },
        {
          "n": "Implement Chain Replication",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            0.8626,
            0.7516,
            1.0,
            0.9444,
            0.6161
          ]
        },
        {
          "n": "Implement Consistent Broadcast",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            1.0,
            0.9266,
            0.0251,
            1.0,
            0.0
          ]
        },
        {
          "n": "Implement CRDT Raft",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            0.9071,
            0.9071,
            0.9071,
            0.9071,
            0.7516
          ]
        },
        {
          "n": "Implement Epidemic Broadcast",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            1.0,
            0.0038,
            1.0,
            1.0,
            0.0038
          ]
        },
        {
          "n": "Implement Gossip Store",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.65,
          "s": 8.0,
          "f": [
            1.0,
            0.0123,
            1.0,
            0.0045,
            0.0
          ]
        },
        {
          "n": "Implement LSM Compaction",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            0.0,
            0.8745
          ]
        },
        {
          "n": "Implement PBFT",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            0.1799,
            0.0513,
            0.1375,
            0.0988,
            0.1799
          ]
        },
        {
          "n": "Implement Raft Log",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            0.2244,
            0.0
          ]
        },
        {
          "n": "Implement Read Repair",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            0.0,
            1.0,
            1.0,
            0.0,
            0.9071
          ]
        },
        {
          "n": "Implement Shard Migration",
          "d": "Implement the algorithm from scratch to meet the specification.",
          "c": 0.7,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            0.1375,
            0.0
          ]
        },
        {
          "n": "Paxos Prepare",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.6,
          "s": 8.0,
          "f": [
            1.0,
            0.1678,
            1.0,
            1.0,
            0.9538
          ]
        },
        {
          "n": "Swim Protocol",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.9744,
            0.0,
            0.9744,
            0.9744,
            0.9744
          ]
        },
        {
          "n": "Twopc Crash",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.8,
          "s": 8.0,
          "f": [
            1.0,
            1.0,
            1.0,
            0.0,
            1.0
          ]
        },
        {
          "n": "Verify Two Phase Commit",
          "d": "Fill in formal proof obligations so the verifier accepts.",
          "c": 0.45,
          "s": 8.0,
          "f": [
            null,
            0.0,
            0.0,
            0.0,
            0.9261
          ]
        },
        {
          "n": "Virtual Nodes",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.5,
          "s": 8.0,
          "f": [
            0.895,
            0.895,
            0.895,
            0.895,
            0.895
          ]
        }
      ]
    },
    {
      "id": "cedar",
      "name": "Authorization",
      "desc": "Agents write Cedar authorization policies and prove security properties in Lean 4.",
      "tasks": [
        {
          "n": "Adversarial Policy Audit",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.65,
          "s": 6.0,
          "f": [
            0.05,
            0.02,
            0.0,
            0.05,
            null
          ]
        },
        {
          "n": "Debug Healthcare Records",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            0.5998,
            0.7041,
            0.02,
            0.5998,
            null
          ]
        },
        {
          "n": "Debug Multi Tenant Authorization",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            0.9,
            0.9,
            0.9,
            0.9,
            null
          ]
        },
        {
          "n": "Debug Recursive Hierarchy Access",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            0.02,
            0.0,
            0.6519,
            0.02,
            null
          ]
        },
        {
          "n": "Find Authorization Bypass",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.15,
          "s": 6.0,
          "f": [
            0.05,
            0.0,
            0.0,
            0.05,
            null
          ]
        },
        {
          "n": "Fix Action Group Conflicts",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.62,
          "s": 8.0,
          "f": [
            0.9,
            0.9,
            0.9,
            0.556,
            null
          ]
        },
        {
          "n": "Fix Ip Time Geo Policies",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.87,
          "s": 8.0,
          "f": [
            0.9,
            0.5199,
            0.5199,
            0.0,
            null
          ]
        },
        {
          "n": "Fix Photo Sharing Bugs",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.82,
          "s": 8.0,
          "f": [
            0.02,
            0.02,
            0.02,
            0.0,
            null
          ]
        },
        {
          "n": "Fix Schema Type Errors",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.48,
          "s": 8.0,
          "f": [
            0.8178,
            0.8178,
            0.9,
            0.8178,
            null
          ]
        },
        {
          "n": "Fix Scope And Condition Bugs",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.65,
          "s": 8.0,
          "f": [
            0.9,
            0.9,
            0.9,
            0.9,
            null
          ]
        },
        {
          "n": "Fix Template Instantiation Bugs",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.85,
          "s": 8.0,
          "f": [
            0.9,
            0.9,
            0.9,
            0.5851,
            null
          ]
        },
        {
          "n": "Fix Unsafe Attribute Access",
          "d": "Find and fix bugs in the implementation until all tests pass.",
          "c": 0.9,
          "s": 8.0,
          "f": [
            0.8205,
            0.02,
            0.02,
            0.02,
            null
          ]
        },
        {
          "n": "Full Hospital Authorization System",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.53,
          "s": 9.0,
          "f": [
            0.8876,
            0.02,
            0.0,
            0.6159,
            null
          ]
        },
        {
          "n": "Implement And Verify Refactoring",
          "d": "Fill in formal proof obligations so the verifier accepts.",
          "c": 0.3,
          "s": 8.0,
          "f": [
            0.3361,
            0.0,
            0.0,
            0.0,
            null
          ]
        },
        {
          "n": "Policy Equivalence Analysis",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.65,
          "s": 8.0,
          "f": [
            0.9724,
            0.8819,
            0.8819,
            0.8819,
            null
          ]
        },
        {
          "n": "Prove Emergency Override Safety",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.15,
          "s": 8.0,
          "f": [
            0.0,
            0.0,
            0.0,
            0.0,
            null
          ]
        },
        {
          "n": "Prove Forbid Overrides Permit",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.15,
          "s": 8.0,
          "f": [
            0.0,
            1.0,
            0.05,
            0.05,
            null
          ]
        },
        {
          "n": "Prove Policy Slicing Soundness",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.15,
          "s": 8.0,
          "f": [
            0.05,
            0.2068,
            0.05,
            0.05,
            null
          ]
        },
        {
          "n": "Prove Schema Validation Soundness",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.15,
          "s": 8.0,
          "f": [
            0.0,
            0.05,
            0.05,
            0.05,
            null
          ]
        },
        {
          "n": "Schema Evolution Migration",
          "d": "Complete the task to pass the automated evaluation.",
          "c": 0.67,
          "s": 8.0,
          "f": [
            0.849,
            0.849,
            0.849,
            0.2125,
            null
          ]
        }
      ]
    }
  ]
};
